
name = "DashDraftjsComponents"
uuid = "1b08a953-4be3-4667-9a23-045dc46b2fab"
authors = ["Yasas Senarath <12231659+ysenarath@users.noreply.github.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
